import { Router } from "express";
import { ElevenLabsClient } from "elevenlabs";

const router = Router();

const MIN_SYNTHESIS_CHARS = 100;
const MAX_SYNTHESIS_CHARS = 150;
const FILLER_BANK = " Echoes of forgotten ages drift through silence. Ancient voices rise and fall like tides against timeless stone.";

if (!process.env.ELEVEN_SECRET) {
  console.warn("[synthesize-voice] WARNING: ELEVEN_SECRET is not set — synthesis requests will fail.");
}

router.post("/synthesize-voice", async (req, res) => {
  console.log("[synthesize-voice] Synthesize Request Received:", req.body);

  const { vocalBlueprint, firstMessage } = req.body as {
    vocalBlueprint?: string;
    firstMessage?: string;
  };

  if (!vocalBlueprint?.trim() || !firstMessage?.trim()) {
    res.status(400).json({ error: "vocalBlueprint and firstMessage are required and must not be empty" });
    return;
  }

  const apiKey = process.env.ELEVEN_SECRET;
  if (!apiKey) {
    res.status(500).json({ error: "ElevenLabs API key not configured on server" });
    return;
  }

  let synthesisText = firstMessage.trim();
  const originalLen = synthesisText.length;

  if (synthesisText.length > MAX_SYNTHESIS_CHARS) {
    synthesisText = synthesisText.slice(0, MAX_SYNTHESIS_CHARS);
    console.log(`[synthesize-voice] Text truncated from ${originalLen} → ${synthesisText.length} chars to conserve API credits`);
  }

  if (synthesisText.length < MIN_SYNTHESIS_CHARS) {
    const needed = MIN_SYNTHESIS_CHARS - synthesisText.length;
    synthesisText = synthesisText + FILLER_BANK.slice(0, needed + 10);
    if (synthesisText.length > MAX_SYNTHESIS_CHARS) {
      synthesisText = synthesisText.slice(0, MAX_SYNTHESIS_CHARS);
    }
    console.log(`[synthesize-voice] Text padded from ${originalLen} → ${synthesisText.length} chars (ElevenLabs min is ${MIN_SYNTHESIS_CHARS})`);
  }

  console.log(`[synthesize-voice] Calling ElevenLabs — text length: ${synthesisText.length} chars, description length: ${vocalBlueprint.length} chars`);

  try {
    const client = new ElevenLabsClient({ apiKey });

    const result = await client.textToVoice.createPreviews({
      voice_description: vocalBlueprint,
      text: synthesisText,
      model_id: "eleven_multilingual_ttv_v2",
    });

    if (!result.previews || result.previews.length === 0) {
      throw new Error("No voice previews generated by ElevenLabs.");
    }

    const preview = result.previews[0];
    console.log(`[synthesize-voice] Voice generated successfully: ${preview.generated_voice_id}`);

    res.json({
      voiceId: preview.generated_voice_id,
      audioBase64: preview.audio_sample,
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[synthesize-voice] ElevenLabs API Error:", message);
    res.status(500).json({ error: message });
  }
});

export default router;
